const worker=new Worker(new URL('./tts.worker.js',import.meta.url),{type:'module'});
const $=s=>document.querySelector(s);let loaded=false,encoded=false,pending=new Map(),files=new Map();
worker.onmessage=e=>{const {type,data}=e.data;if(type==='load:progress'){progress(data);return}if(type==='error'){for(const p of pending.values())p.reject(new Error(data.message));pending.clear();return}const p=pending.get(type);if(p){p.resolve(data);pending.delete(type)}};
function send(type,data={}){return new Promise((resolve,reject)=>{pending.set(type+':complete',{resolve,reject});worker.postMessage({type,data})})}
function status(a,b='',pct=0){$('#stitle').textContent=a;$('#sdetail').textContent=b;$('#bar').style.width=Math.max(0,Math.min(100,pct))+'%'}
function progress(p){if(p.status==='progress'&&p.file){files.set(p.file,{loaded:p.loaded||0,total:p.total||0});let L=0,T=0;for(const v of files.values()){L+=v.loaded;T+=v.total}const pc=T?L/T*100:(p.progress||0);status('Carregando o motor neural…',`${p.file} • ${Math.round(pc)}% do total conhecido`,pc)}}
function wav(samples,sr=24000){const b=new ArrayBuffer(44+samples.length*2),v=new DataView(b),w=(o,s)=>[...s].forEach((c,i)=>v.setUint8(o+i,c.charCodeAt(0)));w(0,'RIFF');v.setUint32(4,36+samples.length*2,true);w(8,'WAVE');w(12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,1,true);v.setUint32(24,sr,true);v.setUint32(28,sr*2,true);v.setUint16(32,2,true);v.setUint16(34,16,true);w(36,'data');v.setUint32(40,samples.length*2,true);let o=44;for(const x of samples){let s=Math.max(-1,Math.min(1,x));v.setInt16(o,s<0?s*32768:s*32767,true);o+=2}return new Blob([b],{type:'audio/wav'})}
async function refAudio(){const a=await fetch(new URL('./thais-reference.wav', import.meta.url)).then(r=>r.arrayBuffer());const ctx=new AudioContext({sampleRate:24000});const d=await ctx.decodeAudioData(a);let x=d.getChannelData(0);if(d.sampleRate!==24000){const off=new OfflineAudioContext(1,Math.ceil(d.duration*24000),24000),buf=off.createBuffer(1,x.length,d.sampleRate);buf.copyToChannel(x,0);const s=off.createBufferSource();s.buffer=buf;s.connect(off.destination);s.start();x=(await off.startRendering()).getChannelData(0)}await ctx.close();return new Float32Array(x)}
(async()=>{try{const g=await send('check_webgpu');$('#gpu').innerHTML=g.available?'<span class="good">✓ WebGPU ativo neste site HTTPS.</span>':'<span class="bad">WebGPU indisponível neste navegador: '+g.reason+'</span>'}catch(e){$('#gpu').textContent=e.message}})();
$('#listen').onclick=()=>$('#reference').play();$('#speed').oninput=()=>$('#speedv').textContent=Number($('#speed').value).toFixed(2)+'×';$('#ex').oninput=()=>$('#exv').textContent=Number($('#ex').value).toFixed(2);
document.querySelectorAll('.preset').forEach(b=>b.onclick=()=>{document.querySelectorAll('.preset').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#ex').value=b.dataset.e;$('#speed').value=b.dataset.s;$('#ex').oninput();$('#speed').oninput()});
$('#generate').onclick=async()=>{const btn=$('#generate'),text=$('#text').value.trim();if(!text)return;btn.disabled=true;try{if(!loaded){status('Carregando o motor neural…','Na primeira vez, aguarde o download completo.',1);const r=await send('load');loaded=true;$('#gpu').innerHTML=r.webgpu?'<span class="good">✓ WebGPU ativo — aceleração por GPU.</span>':'<span class="bad">Motor carregado em WASM — neste aparelho será mais lento.</span>'}if(!encoded){status('Preparando sua voz…','Extraindo a identidade vocal da gravação.',100);const a=await refAudio();await send('encode_speaker',{id:'thais',audioData:a.buffer});encoded=true}status('Gerando com sua voz…','Síntese neural em andamento.',100);const r=await send('generate',{text,speakerId:'thais',exaggeration:Number($('#ex').value)});const blob=wav(new Float32Array(r.waveform)),u=URL.createObjectURL(blob);$('#output').src=u;$('#output').playbackRate=Number($('#speed').value);$('#download').href=u;$('#result').classList.add('show');status('Concluído.','O áudio foi gerado.',100)}catch(e){status('Não foi possível concluir.',e.message,0)}finally{btn.disabled=false}};
